### ISSUE TITLE
pip version > 1.4.x requires --pre flag for installation

### ISSUE THREAD

**Issue by michaelaye** [RyanBalfanz/PyPDS#17]
The versioning of PyPDS does not seem to follow the guidelines for the new (since pip version 1.4) versioning rules to distinguish between release and pre-release versions.
So, with a new pip, currently it needs to be installed like so:

``` bash
pip install --pre pypds
```

Maybe you could update that? Or put a warning somewhere about this? I just lost 20 minutes over that, while I had a pip 1.3.x and the other party a pip 1.5 and it was totally mysterious that the same command did not work on the other computer.

**Comment by RyanBalfanz** [comment]
@michaelaye, thanks for reporting this. I honestly don't know when I'll have time to get to this. Any chance you can submit a Pull Request?

**Comment by michaelaye** [comment]
I don't understand the pip system myself, but I'm happy to submit a pull request to your README.md to warn users about it?

**Comment by RyanBalfanz** [comment]
Merged PR#18 (https://github.com/RyanBalfanz/PyPDS/pull/18)
