### ISSUE TITLE
ImageNotSupportedError exception

### ISSUE THREAD

**Issue by donbright** [RyanBalfanz/PyPDS#20]
Hello

Thanks for this project. Im trying to open

http://www.uahirise.org/PDS/DTM/PSP/ORB_008500_008599/PSP_008520_2085_PSP_009232_2085/DTEEC_008520_2085_009232_2085_A01.IMG

from

http://www.uahirise.org/dtm/dtm.php?ID=PSP_008520_2085

but I get an exception. 

I saved the file to /tmp/x.img and this is the result:

```
>>> labels = p.parse(open_pds('/tmp/x.img'))
>>> pprint.pprint(labels['IMAGE'])
{'BANDS': '1',
 'LINES': '18055',
 'LINE_SAMPLES': '8086',
 'MISSING_CONSTANT': '16#FF7FFFFB#',
 'NOTE': '"Pixel values in this file represent elevations in meters above the martian equipotential surface (Mars 2000 Datum) defined by Smith, et al. (2001). Conversion from pixel units to geophysical units is given by the keyvalues for SCALING_FACTOR and OFFSET. This DTM was produced using ISIS and SOCET Set (copyright BAE Systems) software as described in Kirk et al. (2008)."',
 'OFFSET': '0.0',
 'SAMPLE_BITS': '32',
 'SAMPLE_BIT_MASK': '2#11111111111111111111111111111111#',
 'SAMPLE_TYPE': 'PC_REAL',
 'SCALING_FACTOR': '1.0',
 'VALID_MAXIMUM': '-2293.22',
 'VALID_MINIMUM': '-2821.92'}
>>> from pds.imageextractor import ImageExtractor
>>> ig = ImageExtractor()
>>> img,lbls = ig.extract(open_pds('/tmp/x.img'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pds/imageextractor.py", line 121, in extract
    if self._check_image_is_supported():
  File "/usr/local/lib/python2.7/dist-packages/pds/imageextractor.py", line 186, in _check_image_is_supported
    raise ImageNotSupportedError(errorMessage)
TypeError: __init__() takes exactly 1 argument (2 given)
```

**Comment by godber** [comment]
Any chance you can provide a much smaller equivalent sample?

**Comment by donbright** [comment]
i figured out the problem, pypds doesnt support that Image format. I looked at the PyPDS source code and it says that it only supports certain image types and/or number types, which are not those from this data set. Thanks for replying. Should I close this issue?

i couldnt give a smaller sample at the moment, i dont know enough about the image format they use to generate a small one and all their files are huge that i know of.

**Comment by godber** [comment]
Hi @donbright I was actually asking for another project I am working on `planetaryimage`.

**Comment by donbright** [comment]
you can see here https://github.com/RyanBalfanz/PyPDS/blob/master/pds/imageextractor.py
that PyPDS only supports Sample Types that are Integers. 

The problem with the HiRISE data i linked to is that the Numtype is 32 bit "PC_REAL" which isnt supported. (Basically, 32 bit floating point number, a 'float32' in C or Go)

https://pds.jpl.nasa.gov/documents/sr/AppendixC.pdf

I was able to write a little code to read these using numpy's frombuffer

```
            value = np.frombuffer(sample,dtype=np.float32)
```

but i didnt get very far, nor did i try to integrate into PyPDS

https://github.com/donbright/yllas/blob/master/chunkit.py

not sure if any of that helps.

**Comment by godber** [comment]
Hi @donbright, we should continue this conversation on an issue here: 

https://github.com/planetarypy/planetaryimage/issues 

I will fix it in that project.

**Comment by donbright** [comment]
obsolete
