### ISSUE TITLE
Verify input is valid PDS file

### ISSUE THREAD

**Issue by RyanBalfanz** [RyanBalfanz/PyPDS#3]
Not sure if this is necessary.

Just don't try to read() a non-PDS file if using a readline() optional sentinel. The sentinel only means not needing to break on the END line of the PDS label header when iterating over the lines. The point of abandoning the iteration is to not read more information than necessary. This is especially poignant given than the binary data may dominate the total file size.

**Comment by afrigeri** [comment]
Ryan, an extra check for a valid PDS file is to verify that (RECORD_BYTES \* FILE_RECORDS) is the actual filesize.

**Comment by RyanBalfanz** [comment]
That's a good check thanks for the tip.

When I opened the issue I was considering things like checking file extensions. I'm not 100% sure, but I don't think it's using a sentinel while reading this file. I'll have to look at the code to remind myself exactly what I meant.

Either way, I'll get to adding your extra check. Thanks!

**Comment by RyanBalfanz** [comment]
Fixed by commit 4a60a5.
http://github.com/RyanBalfanz/PyPDS/commit/4a60a56fbc6fc8aebf38473abd963f07d0d833a2
